team-MUMENT/MUMENT-SERVER

src/interfaces/mument/MumentCardViewInterface.ts, src/interfaces/music/MusicMumentListResponseDto.ts, src/interfaces/music/MusicMyMumentResponseDto.ts, src/routes/MumentRouter.ts
- 뮤멘트 카드뷰 인터페이스 생성
- 기존 dto 인터페이스 활용하도록 수정
#16
=> [CHORE] 뮤멘트 카드뷰 인터페이스 통일

src/controllers/UserController.ts, src/interfaces/mument/IsFirstResponseDto.ts, src/services/MumentService.ts, src/services/UserService.ts
처음/다시 태그 판단에서 처음 태그를 선택할 수 있는지 판단하기위한 필드 처리
#19 
- DTO에 firstAvailable 필드 추가
- 처음 들었어요 선택과 관련한 세 가지 케이스 처리
=> [FEAT] 처음 들었어요 선택 가능한지 판단 #19

src/controllers/UserController.ts, src/interfaces/mument/IsFirstResponseDto.ts, src/services/MumentService.ts, src/services/UserService.ts
보관함 나의 뮤멘트 리스트 필터링
보관함 좋아요한 뮤멘트 리스트 필터링
#10 #14
- 보관함 좋아요 & 나의 뮤멘트 리스트 - 필터링
분기문으로 처리하려다 조건이 많아져서 리스트를 합쳐서 필터링 시켰습니다!
- 좋아요 뮤멘트 리스트 -  최신순 정렬 수정
=> [FEAT] 보관함 뮤멘트 리스트 필터링 

src/controllers/MumentController.ts, src/modules/responseMessage.ts, src/routes/MumentRouter.ts, src/routes/UserRouter.ts, src/services/MumentService.ts, src/services/MusicService.ts, src/services/UserService.ts, yarn.lock
뮤멘트 수정합니다.
#27
- validator 사용하여 필수 필드 받기
- 공개글이었다가 비밀글로 수정한 경우 : 해당 뮤멘트의 likeCount를 0으로 초기화, 입력받은 값으로 Mument 및 Like모델의 mument에서 삭제
- 그외의 경우 : 입력받은 값으로 Mument 및 Like 모델 업데이트
- Mument update : mumentId와 일치하는 뮤멘트를 업데이트
- Like update : 모든 Like 다큐먼트에 대해 mument 리스트 내부의 값을 업데이트
=> [FEAT] 뮤멘트 수정하기 구현 #27

src/interfaces/mument/IsFirstResponseDto.ts, src/services/MumentService.ts
=> [CHORE] 변수명 컨벤션 수정 #19 #25

src/controllers/UserController.ts, src/interfaces/mument/MumentCardViewInterface.ts, src/interfaces/mument/MumentResponseDto.ts, src/services/MumentService.ts, src/services/MusicService.ts, src/services/UserService.ts
=> [FEAT] 곡 상세보기&나의 히스토리 태그 개수 처리

src/controllers/MumentController.ts, src/controllers/MusicController.ts, src/interfaces/music/MusicMyMumentResponseDto.ts, src/services/MumentService.ts, src/services/MusicService.ts
=> [HOTFIX] Typescript 에러 해결 #38

src/routes/UserRouter.ts
=> [HOTFIX] 라우터 오타 수정

src/controllers/MumentController.ts, src/interfaces/mument/TodayMumentResponseDto.ts, src/modules/responseMessage.ts, src/modules/serviceReturnConstant.ts, src/routes/MumentRouter.ts, src/services/MumentService.ts
- 오늘 날짜를 가져온 후, 오늘 날짜의 정각으로 시간으로 변경합니다
- utc로 변경한 후, 디비에 저장된 시간과 조회하여 동일한 시간의 document를 가져옵니다
- 디비에 당일과 일치하는 날짜가 없다면 204 코드를 리턴해줍니다
#47
=> [FEAT] 오늘의 뮤멘트 조회 구현

src/controllers/MumentController.ts, src/interfaces/mument/TodayBannerResponseDto.ts, src/modules/responseMessage.ts, src/routes/MumentRouter.ts, src/services/MumentService.ts
- 이번주 월요일 자정 날짜를 생성합니다
- 날짜를 utc로 가공해줍니다
- db의 display date가 같은 배너를 조회해옵니다
- 조회 결과가 없으면 204 code를 리턴합니다
#49
=> [FEAT] 배너 조회 구현

src/controllers/MumentController.ts, src/interfaces/mument/AgainMumentResponseDto.ts, src/modules/responseMessage.ts, src/routes/MumentRouter.ts, src/services/MumentService.ts
- 오늘의 날짜를 생성한 후, 자정 시간으로 수정
- 해당 시간을 utc로 수정
- displayDate가 해당 시간과 일치하는 document 조회
- 조회 결과 없을 시 204 리턴
#51
=> [FEAT] 다시 들은 곡의 뮤멘트 조회 구현

src/services/MumentService.ts
=> [HOTFIX] 시간 관련 코드 수정 #54

src/services/MumentService.ts
=> [HOTFIX] 비밀글 로직 처리 수정

tsconfig.json
=> [HOTFIX] 파일명 변경 casing 오류 해결

package.json, src/config/index.ts, src/controllers/AuthController.ts, src/controllers/MumentController.ts, src/controllers/MusicController.ts, src/controllers/UserController.ts, src/library/slackWebhook.ts, src/services/MusicService.ts, yarn.lock
=> [ADD] 슬랙 웹훅 코드 추가

package-lock.json, package.json, src/config/index.ts, src/index.ts, src/interfaces/common/PostBaseResponseDto.ts, src/interfaces/mument/MumentHistoryResponseDto.ts, src/interfaces/mument/MumentResponseDto.ts, src/interfaces/music/MusicMyMumentResponseDto.ts, src/loaders/db.ts, src/modules/dummyData.ts, src/modules/pool.ts, src/services/AuthService.ts, src/services/MumentService.ts, src/services/MusicService.ts, src/services/UserService.ts, yarn.lock
- MongoDB -> MySQL로 DB 변경
- config, loaders RDS setting
- service 로직 기존 DB 사용 부분 임시 주석 처리
- 쿼리를 사용하는 모듈 파일 생성 - pool
- 임시 더미데이터 파일 생성 (마이그레이션 동안만 쓰임)
#63 
modules/pool.ts에 쿼리 사용 시 쓸 수 있는 모듈 두 가지를 생성했습니다. 
사용 예시는 UserService에 임시로 써두었습니다!
=> [REFACTOR] DB migration Setting

.eslintrc.json, .gitignore, package-lock.json, package.json, src/controllers/AuthController.ts, src/controllers/MumentController.ts, src/controllers/MusicController.ts, src/index.ts, src/interfaces/auth/AppleResponseDto.ts, src/interfaces/music/MusicResponseDto.ts, src/library/appleSignIn.ts, src/modules/pool.ts, src/modules/responseMessage.ts, src/modules/serviceReturnConstant.ts, src/routes/AuthRouter.ts, src/services/AuthService.ts, src/services/MumentService.ts, src/services/MusicService.ts, src/services/UserService.ts, test/UserService.spec.ts, tsconfig.json, yarn.lock
1. apple music OpenAPI를 사용하여 곡 검색으로 리팩토링
2. 처음/다시 판단 API & 뮤멘트 기록하기 API 에서 SQL query 사용 로직으로 변경
#15 
- 애플 API를 사용하기 위해 필요한 개발자 토큰을 만드는 라이브러리 코드를 library에 만들었습니다. 
- apple server status 대응 - 애플 서버로부터 200, 401, 500 을 받을 수 있어서 3가지 상수를 이용해서 핸들링했습니다.
- apple로부터 받은 데이터를 musicResponseDto에 맞게 가공하여 response를 보냈습니다!
- .gitignore에 등록한 몇 가지 파일은 칸반에 적어두었습니다!
- apple music에서 검색 결과로 최대 25개까지 가능하다고합니다!
- 이전에 push한 것들을 pr을 안남겼어서 약간 섞여 있는 것 같아요..!! UserService 테스트 코드 간단하게 짜본 것도 올라갔습니다 :)
---
- 처음/다시 판단 API 에서는 library로 만들어둔 pool query 처리함수를 썼고, 뮤멘트 기록하기 API 에서는 쿼리가 2개여서 트랜잭션으로 처리하기 위해 개별적으로 pool query 로직을 작성했습니다!
* dev_rdb로 머지
=> [REFACTOR] 곡 검색하기 - openAPI 사용한 리팩토링 & 처음/다시 선택, 뮤멘트 기록하기 - sql query 사용 로직으로 변경

src/services/MumentService.ts
뮤멘트 삭제하기 SQL사용으로 리팩토링
#74 
- mument 테이블에서 mumentId row 삭제하기 → is_deleted=1로 만듦
- mument_tag 테이블에서 mumentId row들 삭제하기
- like 테이블에서 mumentId row들 삭제하기
=> [REFACTOR] 뮤멘트 상세보기 - sql query 사용 로직으로 변경

src/interfaces/auth/JwtPayload.ts, src/library/jwtHandler.ts, src/library/kakaoAuth.ts, src/modules/jwtStatus.ts, src/modules/serviceReturnConstant.ts, yarn.lock
카카오 로그인시, authentication code로 kakao token 발급, kakao token으로 유저 프로파일 조회해오는 kakao auth 라이브러리 추가
새로운 access token, refresh token을 생성, token 해독 및 에러 처리를 하는 JWT 라이브러리 추가
#77, #79
=> [ADD] 카카오 로그인 관련 라이브러리, JWT 토큰 관련 라이브러리 추가

src/interfaces/auth/AuthTokenResponseDto.ts, src/interfaces/auth/JwtPayload.ts, src/interfaces/user/UserInfoRDB.ts, src/modules/db/Auth.ts, src/modules/serviceReturnConstant.ts, src/services/AuthService.ts
- provider가 kakao 일 때의 로직이랑, token 발급 로직 완료
- user table 스키마 수정 및 수정사항 interface에 반영
- access token과 refresh token을 리턴하는 response dto 추가
#81
=> [FEAT] 카카오 로그인

src/controllers/MumentController.ts, src/interfaces/mument/NoticeInfoRDB.ts, src/modules/responseMessage.ts, src/modules/serviceReturnConstant.ts, src/routes/MumentRouter.ts, src/services/MumentService.ts
- 공지사항 리스트 조회 API 라우터 서비스로직 컨트롤러
- 공지사항 상세보기 API 라우터 서비스로직 컨트롤러
#98 
공지사항 리스트 -> 최신순 조회, 날짜 가공 reduce 사용
=> [FEAT] 공지사항 리스트 조회 API & 공지사항 상세보기 API

src/services/MumentService.ts
=> [CHORE] 날짜 포매팅 형식 수정

src/library/jwtHandler.ts
- 토큰 만료시 if문에서 스트링으로 대조하지 않아, 의도한 메세지가 전송되지 않는 에러를 수정하였습니다.
=> [FIX] 토큰 만료시 의도한 메세지가 뜨지 않는 에러 수정

dist/services/MumentService.js, src/services/MumentService.ts
- 쿼리문에 해당 뮤멘트의 id도 가져오도록 추가했습니다.
=> [MOD] 쿼리문에 id 추가

src/controllers/UserController.ts, src/interfaces/user/UserDeleteResponseDto.ts, src/middlewares/uploadImage.ts, src/routes/UserRouter.ts, src/services/UserService.ts
=> [HOTFIX] profileId를 userName으로 통일 #154

src/routes/MumentRouter.ts
=> [MOD] 신고 사유 express validater 수정

src/controllers/MusicController.ts, src/routes/MusicRouter.ts, src/services/MusicService.ts
- 페이지네이션 수정
- 나의 비밀글도 보이도록 수정
#177
=> [MOD] 곡 상세보기 수정

src/controllers/MumentController.ts, src/routes/MumentRouter.ts, src/services/MumentService.ts, src/services/MusicService.ts
- 모든 뮤멘트 비밀글 관련 코드 수정
- 히스토리 페이지네이션 코드 제거
#177
=> [MOD] 페이지네이션 관련 코드 수정
